[CmdletBinding()]
param(
    [Parameter(Mandatory = $true)]
    [string]$ProjectPath,

    [string]$KiCadCliPath = '',

    [string]$OutputRoot = ''
)

$ErrorActionPreference = 'Stop'
. (Join-Path -Path $PSScriptRoot -ChildPath 'kicad_automation_common.ps1')

try {
    $context = New-KiCadScriptContext -ProjectPath $ProjectPath -TaskName 'drill_NOT_FINAL' -FolderKind 'fabrication' -OutputRoot $OutputRoot -KiCadCliPath $KiCadCliPath
    $files = Find-KiCadProjectFiles -ProjectPath $context.ProjectPath
    $projectFilePath = Select-SingleKiCadProjectFile -ProjectFiles $files
    $pcbPath = Select-MainPcbFile -ProjectFiles $files -ProjectFilePath $projectFilePath

    if (-not $pcbPath) {
        throw 'No .kicad_pcb file was found. Drill export was not run.'
    }

    $drillFolder = Join-Path -Path $context.OutputFolder -ChildPath 'drill'
    New-Item -ItemType Directory -Path $drillFolder | Out-Null
    $markerPath = Write-NotFinalMarker -OutputFolder $context.OutputFolder -Reason 'Drill export was generated by script and has not passed all fabrication release gates.'

    $arguments = @('pcb', 'export', 'drill', '--output', $drillFolder, $pcbPath)
    $result = Invoke-KiCadCliCommand -KiCadCliPath $context.KiCadCliPath -Arguments $arguments -LogPath $context.LogPath

    $summaryPath = Join-Path -Path $context.OutputFolder -ChildPath 'drill_export_summary.md'
    $status = if ($result.ExitCode -eq 0) { 'EXPORTED_NOT_FINAL' } else { 'FAILED' }
    Write-SummaryMarkdown -Path $summaryPath -Lines @(
        '# Drill Export Summary',
        '',
        "Status: $status",
        "Exit code: $($result.ExitCode)",
        ('Project: `{0}`' -f $context.ProjectPath),
        ('PCB: `{0}`' -f $pcbPath),
        ('Drill folder: `{0}`' -f $drillFolder),
        ('Not-final marker: `{0}`' -f $markerPath),
        ('Command log: `{0}`' -f $result.CommandLog),
        '',
        'These outputs are not final manufacturing files.'
    )

    Write-Output "Summary: drill export status $status, exit code $($result.ExitCode)."
    Write-Output "Output folder: $($context.OutputFolder)"
    if ($result.ExitCode -ne 0) {
        exit $result.ExitCode
    }
    exit 0
} catch {
    Write-Error $_.Exception.Message
    exit 1
}
