[CmdletBinding()]
param(
    [Parameter(Mandatory = $true)]
    [string]$ProjectPath,

    [string]$KiCadCliPath = '',

    [string]$OutputRoot = ''
)

$ErrorActionPreference = 'Stop'
. (Join-Path -Path $PSScriptRoot -ChildPath 'kicad_automation_common.ps1')

try {
    $context = New-KiCadScriptContext -ProjectPath $ProjectPath -TaskName 'step_NOT_FINAL' -FolderKind 'fabrication' -OutputRoot $OutputRoot -KiCadCliPath $KiCadCliPath
    $files = Find-KiCadProjectFiles -ProjectPath $context.ProjectPath
    $projectFilePath = Select-SingleKiCadProjectFile -ProjectFiles $files
    $pcbPath = Select-MainPcbFile -ProjectFiles $files -ProjectFilePath $projectFilePath

    if (-not $pcbPath) {
        throw 'No .kicad_pcb file was found. STEP export was not run.'
    }

    $projectName = [System.IO.Path]::GetFileNameWithoutExtension($projectFilePath)
    $stepPath = Join-Path -Path $context.OutputFolder -ChildPath "${projectName}_NOT_FINAL.step"
    $markerPath = Write-NotFinalMarker -OutputFolder $context.OutputFolder -Reason 'STEP export was generated by script and has not passed all mechanical and fabrication release gates.'

    $arguments = @('pcb', 'export', 'step', '--output', $stepPath, $pcbPath)
    $result = Invoke-KiCadCliCommand -KiCadCliPath $context.KiCadCliPath -Arguments $arguments -LogPath $context.LogPath

    $summaryPath = Join-Path -Path $context.OutputFolder -ChildPath 'step_export_summary.md'
    $status = if ($result.ExitCode -eq 0) { 'EXPORTED_NOT_FINAL' } else { 'FAILED' }
    Write-SummaryMarkdown -Path $summaryPath -Lines @(
        '# STEP Export Summary',
        '',
        "Status: $status",
        "Exit code: $($result.ExitCode)",
        ('Project: `{0}`' -f $context.ProjectPath),
        ('PCB: `{0}`' -f $pcbPath),
        ('STEP file: `{0}`' -f $stepPath),
        ('Not-final marker: `{0}`' -f $markerPath),
        ('Command log: `{0}`' -f $result.CommandLog),
        '',
        'This output is not a final mechanical release file.'
    )

    Write-Output "Summary: STEP export status $status, exit code $($result.ExitCode)."
    Write-Output "Output folder: $($context.OutputFolder)"
    if ($result.ExitCode -ne 0) {
        exit $result.ExitCode
    }
    exit 0
} catch {
    Write-Error $_.Exception.Message
    exit 1
}
