#!/usr/bin/env python3
"""Build global and startup history indexes.

The script scans history Markdown files and writes generated indexes. It never
deletes records and never edits KiCad project source files.
"""

from __future__ import annotations

import argparse
import json
from collections import defaultdict
from datetime import datetime
from pathlib import Path


def rel(path: Path, root: Path) -> str:
    return str(path.relative_to(root)).replace("/", "\\")


def title_for(path: Path) -> str:
    try:
        for line in path.read_text(encoding="utf-8", errors="replace").splitlines():
            if line.startswith("# "):
                return line[2:].strip()
    except OSError:
        pass
    return path.stem.replace("_", " ").title()


def collect_history(root: Path) -> list[dict[str, object]]:
    records: list[dict[str, object]] = []
    scan_roots = [root / "02_HISTORY", root / "04_KICAD_PROJECTS" / "active"]
    for scan_root in scan_roots:
        if not scan_root.exists():
            continue
        for path in sorted(scan_root.rglob("*.md"), key=lambda item: str(item).lower()):
            if "__pycache__" in path.parts:
                continue
            rel_path = rel(path, root)
            if scan_root.name == "active" and "\\history\\" not in rel_path.lower():
                continue
            records.append(
                {
                    "path": rel_path,
                    "title": title_for(path),
                    "size_bytes": path.stat().st_size,
                    "scope": "project" if "\\active\\" in rel_path.lower() else "global",
                    "bucket": bucket_for(rel_path),
                }
            )
    return records


def bucket_for(rel_path: str) -> str:
    parts = rel_path.split("\\")
    if parts[0] == "02_HISTORY" and len(parts) > 1:
        return parts[1]
    if "history" in parts:
        idx = parts.index("history")
        if len(parts) > idx + 1:
            return f"project/{parts[idx + 1]}"
    return "other"


def build_markdown(data: dict[str, object]) -> str:
    records = data["records"]  # type: ignore[index]
    by_bucket: dict[str, list[dict[str, object]]] = defaultdict(list)
    for record in records:
        by_bucket[record["bucket"]].append(record)

    lines = [
        "# Master History Index",
        "",
        "Status: `AUTO_BUILT`",
        "",
        f"Generated: `{data['generated_at']}`",
        "",
        "This file is generated by `03_TOOLS/scripts/indexing/build_history_index.py`.",
        "",
        "## Rules",
        "",
        "- History stores evidence of what happened: sessions, commands, audits, verification runs, failures, issues, and AI quality records.",
        "- Durable reusable lessons belong in memory after evidence exists.",
        "- Do not store secrets, credentials, API keys, private tokens, or license keys.",
        "- Do not delete prior history records.",
        "",
        "## Buckets",
        "",
    ]
    for bucket in sorted(by_bucket):
        lines.append(f"- `{bucket}`: {len(by_bucket[bucket])} markdown files")
    lines.extend(["", "## Records", ""])
    for record in records:
        lines.append(f"- `{record['path']}` - {record['title']}")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description="Build KiCad Engine history indexes.")
    parser.add_argument("--repo-root", default=".", help="Repository root path.")
    args = parser.parse_args()

    root = Path(args.repo_root).resolve()
    data = {
        "generated_at": datetime.now().isoformat(timespec="seconds"),
        "repo_root": str(root),
        "records": collect_history(root),
    }

    startup_dir = root / "00_CODEX_START"
    history_dir = root / "02_HISTORY"
    startup_dir.mkdir(parents=True, exist_ok=True)
    history_dir.mkdir(parents=True, exist_ok=True)

    markdown = build_markdown(data)
    (history_dir / "MASTER_HISTORY_INDEX.md").write_text(markdown, encoding="utf-8")
    (startup_dir / "HISTORY_INDEX.generated.md").write_text(markdown, encoding="utf-8")
    (startup_dir / "HISTORY_INDEX.generated.json").write_text(
        json.dumps(data, indent=2), encoding="utf-8"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
