#!/usr/bin/env python3
"""Build a safe, read-only repository structure index.

This script scans the KiCad Engine workspace and writes generated Markdown and
JSON indexes. It does not modify KiCad design files or installed KiCad folders.
"""

from __future__ import annotations

import argparse
import json
from datetime import datetime
from pathlib import Path


SKIP_DIRS = {
    ".git",
    "__pycache__",
    "node_modules",
    ".venv",
    "venv",
    "env",
}


def rel(path: Path, root: Path) -> str:
    return str(path.relative_to(root)).replace("/", "\\")


def top_level_entries(root: Path) -> list[dict[str, object]]:
    entries: list[dict[str, object]] = []
    for child in sorted(root.iterdir(), key=lambda item: item.name.lower()):
        if child.name in SKIP_DIRS:
            continue
        item: dict[str, object] = {
            "name": child.name,
            "path": rel(child, root),
            "type": "directory" if child.is_dir() else "file",
        }
        if child.is_dir():
            children = [p for p in child.iterdir() if p.name not in SKIP_DIRS]
            item["item_count"] = len(children)
            item["has_readme"] = (child / "README.md").exists()
            item["has_index"] = (child / "INDEX.md").exists()
        else:
            item["size_bytes"] = child.stat().st_size
        entries.append(item)
    return entries


def generated_index_paths(root: Path) -> list[str]:
    paths: list[str] = []
    for pattern in ("*.generated.md", "*.generated.json"):
        paths.extend(rel(path, root) for path in root.glob(f"00_CODEX_START/{pattern}"))
    return sorted(paths)


def build_markdown(data: dict[str, object]) -> str:
    lines = [
        "# Repository Index",
        "",
        "Status: `AUTO_BUILT`",
        "",
        f"Generated: `{data['generated_at']}`",
        "",
        "This file is generated by `03_TOOLS/scripts/indexing/build_repo_index.py`.",
        "",
        "## Top-Level Entries",
        "",
        "| Path | Type | Items | README | INDEX |",
        "| --- | --- | ---: | --- | --- |",
    ]
    for item in data["top_level_entries"]:  # type: ignore[index]
        if item["type"] == "directory":
            lines.append(
                f"| `{item['path']}` | directory | {item.get('item_count', 0)} | "
                f"{'yes' if item.get('has_readme') else 'no'} | "
                f"{'yes' if item.get('has_index') else 'no'} |"
            )
        else:
            lines.append(f"| `{item['path']}` | file | - | - | - |")
    lines.extend(["", "## Generated Startup Indexes", ""])
    for path in data["generated_indexes"]:  # type: ignore[index]
        lines.append(f"- `{path}`")
    lines.extend(
        [
            "",
            "## Safe Use",
            "",
            "- Treat this as an inventory aid, not proof that any engineering claim is verified.",
            "- Do not edit KiCad design files based only on this index.",
            "- Rebuild after structure changes.",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description="Build KiCad Engine repo indexes.")
    parser.add_argument("--repo-root", default=".", help="Repository root path.")
    parser.add_argument(
        "--output-dir",
        default="00_CODEX_START",
        help="Directory for generated startup index outputs.",
    )
    args = parser.parse_args()

    root = Path(args.repo_root).resolve()
    output_dir = (root / args.output_dir).resolve()
    output_dir.mkdir(parents=True, exist_ok=True)

    data = {
        "generated_at": datetime.now().isoformat(timespec="seconds"),
        "repo_root": str(root),
        "top_level_entries": top_level_entries(root),
        "generated_indexes": generated_index_paths(root),
    }

    (output_dir / "REPO_INDEX.generated.json").write_text(
        json.dumps(data, indent=2), encoding="utf-8"
    )
    (output_dir / "REPO_INDEX.generated.md").write_text(
        build_markdown(data), encoding="utf-8"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
