#!/usr/bin/env python3
"""Build global and startup memory indexes.

The script scans memory Markdown files and writes generated indexes. It never
deletes history or edits KiCad project source files.
"""

from __future__ import annotations

import argparse
import json
from datetime import datetime
from pathlib import Path


def rel(path: Path, root: Path) -> str:
    return str(path.relative_to(root)).replace("/", "\\")


def title_for(path: Path) -> str:
    try:
        for line in path.read_text(encoding="utf-8", errors="replace").splitlines():
            if line.startswith("# "):
                return line[2:].strip()
    except OSError:
        pass
    return path.stem.replace("_", " ").title()


def collect_memory(root: Path) -> list[dict[str, object]]:
    records: list[dict[str, object]] = []
    scan_roots = [root / "01_MEMORY", root / "04_KICAD_PROJECTS" / "active"]
    for scan_root in scan_roots:
        if not scan_root.exists():
            continue
        for path in sorted(scan_root.rglob("*.md"), key=lambda item: str(item).lower()):
            if "__pycache__" in path.parts:
                continue
            if scan_root.name == "active" and "\\memory\\" not in str(path).replace("/", "\\").lower():
                continue
            records.append(
                {
                    "path": rel(path, root),
                    "title": title_for(path),
                    "size_bytes": path.stat().st_size,
                    "scope": "project" if "\\active\\" in rel(path, root).lower() else "global",
                }
            )
    return records


def build_markdown(data: dict[str, object]) -> str:
    records = data["records"]  # type: ignore[index]
    global_records = [r for r in records if r["scope"] == "global"]
    project_records = [r for r in records if r["scope"] == "project"]
    lines = [
        "# Master Memory Index",
        "",
        "Status: `AUTO_BUILT`",
        "",
        f"Generated: `{data['generated_at']}`",
        "",
        "This file is generated by `03_TOOLS/scripts/indexing/build_memory_index.py`.",
        "",
        "## Rules",
        "",
        "- Memory stores durable lessons, preferences, verified workflows, and reusable project decisions.",
        "- Commands, transient failures, and raw verification output belong in history, not memory.",
        "- Do not store secrets, credentials, API keys, private tokens, or license keys.",
        "- Mark entries `UNVERIFIED` unless backed by file evidence, command output, datasheets, or human confirmation.",
        "",
        f"## Global Memory Files ({len(global_records)})",
        "",
    ]
    for record in global_records:
        lines.append(f"- `{record['path']}` - {record['title']}")
    lines.extend(["", f"## Project Memory Files ({len(project_records)})", ""])
    for record in project_records:
        lines.append(f"- `{record['path']}` - {record['title']}")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description="Build KiCad Engine memory indexes.")
    parser.add_argument("--repo-root", default=".", help="Repository root path.")
    args = parser.parse_args()

    root = Path(args.repo_root).resolve()
    data = {
        "generated_at": datetime.now().isoformat(timespec="seconds"),
        "repo_root": str(root),
        "records": collect_memory(root),
    }

    startup_dir = root / "00_CODEX_START"
    memory_dir = root / "01_MEMORY"
    startup_dir.mkdir(parents=True, exist_ok=True)
    memory_dir.mkdir(parents=True, exist_ok=True)

    markdown = build_markdown(data)
    (memory_dir / "MASTER_MEMORY_INDEX.md").write_text(markdown, encoding="utf-8")
    (startup_dir / "MEMORY_INDEX.generated.md").write_text(markdown, encoding="utf-8")
    (startup_dir / "MEMORY_INDEX.generated.json").write_text(
        json.dumps(data, indent=2), encoding="utf-8"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
