#!/usr/bin/env python3
"""Create component database Markdown and JSON stubs for a new part.

The script uses user-provided metadata only. It does not scrape, download,
parse PDFs, or verify engineering values.
"""

from __future__ import annotations

import argparse
import json
import re
from datetime import date
from pathlib import Path


UNKNOWN = "Unknown - requires source verification"


def clean_token(value: str) -> str:
    value = value.strip() or "UNKNOWN"
    value = re.sub(r"[^A-Za-z0-9]+", "_", value).strip("_")
    return value.upper() or "UNKNOWN"


def optional(value: str | None) -> str:
    return value.strip() if value and value.strip() else UNKNOWN


def build_record(args: argparse.Namespace) -> dict:
    part_number = optional(args.part_number)
    vendor = optional(args.vendor)
    record_id = f"{clean_token(vendor)}_{clean_token(part_number)}"
    return {
        "record_id": record_id,
        "part_number": part_number,
        "vendor": vendor,
        "family": optional(args.family),
        "category": optional(args.category) if args.category else "99_UNVERIFIED_INBOX",
        "package": optional(args.package),
        "kicad_symbol_candidates": [UNKNOWN],
        "kicad_footprint_candidates": [UNKNOWN],
        "kicad_3d_model_candidates": [UNKNOWN],
        "datasheet_local_path": optional(args.datasheet_local_path),
        "datasheet_source_url": optional(args.datasheet_url),
        "verified_status": "UNVERIFIED_PLACEHOLDER",
        "verification_flags": ["UNVERIFIED_PLACEHOLDER"],
        "pinout_status": "UNVERIFIED_PLACEHOLDER",
        "footprint_status": "UNVERIFIED_FOOTPRINT",
        "layout_notes": [UNKNOWN],
        "power_notes": [UNKNOWN],
        "communication_notes": [UNKNOWN],
        "common_mistakes": [
            "Treating this generated placeholder as verified design data.",
            "Assigning a footprint before checking the exact package drawing.",
            "Using a symbol before every pin is checked against the datasheet.",
        ],
        "ai_warnings": [
            "Do not use this record for schematic, footprint, PCB, BOM, or manufacturing decisions until source verification is complete.",
            "Candidate KiCad symbols and footprints must be verified separately.",
        ],
        "suitable_use_cases": [UNKNOWN],
        "not_suitable_use_cases": [UNKNOWN],
        "required_external_parts": [UNKNOWN],
        "reference_circuits": [UNKNOWN],
        "known_errata": [UNKNOWN],
        "source_confidence": "UNVERIFIED_PLACEHOLDER",
        "last_updated": date.today().isoformat(),
        "notes": [
            "Generated by 13_PART_INGESTION/scripts/create_part_record_stub.py.",
            "User-provided source links and local paths are pointers only; no PDF redistribution is implied.",
        ],
    }


def markdown_for(record: dict) -> str:
    lines = [
        f"# Component Record: {record['part_number']}",
        "",
        "Status: UNVERIFIED_PLACEHOLDER",
        "",
        "## Identity",
        "",
        f"- Record ID: `{record['record_id']}`",
        f"- Part number: {record['part_number']}",
        f"- Vendor: {record['vendor']}",
        f"- Family: {record['family']}",
        f"- Category: {record['category']}",
        f"- Package: {record['package']}",
        "",
        "## Sources",
        "",
        f"- Datasheet source URL: {record['datasheet_source_url']}",
        f"- Datasheet local path: {record['datasheet_local_path']}",
        "- Redistribution status: Unknown - requires human review",
        "",
        "## KiCad Candidates",
        "",
        f"- Symbol candidates: {', '.join(record['kicad_symbol_candidates'])}",
        f"- Footprint candidates: {', '.join(record['kicad_footprint_candidates'])}",
        f"- 3D model candidates: {', '.join(record['kicad_3d_model_candidates'])}",
        "",
        "## Verification Status",
        "",
        f"- Verified status: {record['verified_status']}",
        f"- Pinout status: {record['pinout_status']}",
        f"- Footprint status: {record['footprint_status']}",
        f"- Source confidence: {record['source_confidence']}",
        "",
        "## Design Notes",
        "",
        "### Layout Notes",
        *[f"- {item}" for item in record["layout_notes"]],
        "",
        "### Power Notes",
        *[f"- {item}" for item in record["power_notes"]],
        "",
        "### Communication Notes",
        *[f"- {item}" for item in record["communication_notes"]],
        "",
        "### Required External Parts",
        *[f"- {item}" for item in record["required_external_parts"]],
        "",
        "## Common Mistakes",
        "",
        *[f"- {item}" for item in record["common_mistakes"]],
        "",
        "## AI Warnings",
        "",
        *[f"- {item}" for item in record["ai_warnings"]],
        "",
        "## Open Verification Work",
        "",
        "- Verify exact datasheet revision.",
        "- Extract pinout from source.",
        "- Extract electrical limits from source.",
        "- Extract package drawing and footprint requirements from source.",
        "- Verify KiCad symbol and footprint candidates.",
        "- Add layout warnings with citations.",
        "",
    ]
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description="Create component record Markdown and JSON stubs.")
    parser.add_argument("--part-number")
    parser.add_argument("--vendor")
    parser.add_argument("--family")
    parser.add_argument("--category")
    parser.add_argument("--package")
    parser.add_argument("--datasheet-url")
    parser.add_argument("--datasheet-local-path")
    parser.add_argument("--output-dir", required=True)
    args = parser.parse_args()

    output_dir = Path(args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    record = build_record(args)
    stem = clean_token(record["part_number"])
    md_path = output_dir / f"{stem}_COMPONENT_RECORD.md"
    json_path = output_dir / f"{stem}_COMPONENT_RECORD.json"
    md_path.write_text(markdown_for(record), encoding="utf-8")
    json_path.write_text(json.dumps(record, indent=2) + "\n", encoding="utf-8")
    print(json.dumps({"markdown": str(md_path), "json": str(json_path), "status": "UNVERIFIED_PLACEHOLDER"}))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())

