#!/usr/bin/env python3
"""Build a read-only KiCad 3D model index."""

from __future__ import annotations

import argparse
from pathlib import Path

from kicad_library_common import (
    default_output_dir,
    detect_kicad_root,
    ensure_safe_output_dir,
    fail,
    kicad_share_root,
    utc_stamp,
    write_json,
    write_markdown,
)


MODEL_EXTENSIONS = {".step", ".stp", ".wrl", ".iges", ".igs"}


def build_index(kicad_root: Path) -> dict[str, object]:
    share = kicad_share_root(kicad_root)
    models_root = share / "3dmodels"
    if not models_root.exists():
        fail(f"3D model root not found: {models_root}")

    folders = []
    models = []
    for folder in sorted(models_root.glob("*.3dshapes")):
        files = [p for p in sorted(folder.iterdir()) if p.is_file() and p.suffix.lower() in MODEL_EXTENSIONS]
        counts = {}
        for file_path in files:
            suffix = file_path.suffix.lower().lstrip(".")
            counts[suffix] = counts.get(suffix, 0) + 1
            models.append(
                {
                    "library": folder.stem,
                    "model": file_path.name,
                    "path": str(file_path),
                    "extension": file_path.suffix.lower(),
                    "size_bytes": file_path.stat().st_size,
                }
            )
        folders.append({"library": folder.stem, "path": str(folder), "model_count": len(files), "extension_counts": counts})

    extension_totals = {}
    for model in models:
        ext = model["extension"].lstrip(".")
        extension_totals[ext] = extension_totals.get(ext, 0) + 1

    return {
        "generated_at": utc_stamp(),
        "kicad_root": str(kicad_root),
        "models_root": str(models_root),
        "summary": {
            "model_folders": len(folders),
            "models_indexed": len(models),
            "extension_totals": extension_totals,
        },
        "folders": folders,
        "models": models,
        "safety": [
            "Read-only inspection of KiCad stock 3D model files.",
            "No KiCad install files are modified.",
        ],
    }


def write_summary(output_dir: Path, index: dict[str, object]) -> None:
    summary = index["summary"]
    lines = [
        "# 3D Model Index Summary",
        "",
        f"Generated: {index['generated_at']}",
        "",
        f"KiCad root: `{index['kicad_root']}`",
        f"3D model root: `{index['models_root']}`",
        "",
        "## Counts",
        "",
        f"- 3D model folders: {summary['model_folders']}",
        f"- Models indexed: {summary['models_indexed']}",
        f"- Extension totals: `{summary['extension_totals']}`",
        "",
        "## Largest 3D Model Folders",
        "",
        "| Library | Models | Path |",
        "| --- | ---: | --- |",
    ]
    folders = sorted(index["folders"], key=lambda row: row["model_count"], reverse=True)[:25]
    for row in folders:
        lines.append(f"| `{row['library']}` | {row['model_count']} | `{row['path']}` |")
    lines.extend(
        [
            "",
            "## Safety",
            "",
            "- This summary was generated by read-only filesystem inspection.",
            "- A 3D model match is visual/mechanical evidence only; it does not verify pad geometry.",
        ]
    )
    write_markdown(output_dir / "3d_model_summary.md", lines)


def main() -> int:
    parser = argparse.ArgumentParser(description="Build a read-only KiCad 3D model index.")
    parser.add_argument("--kicad-root", help="KiCad install root. Defaults to detected KiCad 9 root.")
    parser.add_argument("--version", default="9.0", help="KiCad config version. Default: 9.0")
    parser.add_argument("--output-dir", default=str(default_output_dir()), help="Generated index output folder.")
    args = parser.parse_args()

    kicad_root = detect_kicad_root(args.kicad_root, args.version)
    if not kicad_root:
        fail("KiCad root not found. Pass --kicad-root.")
    output_dir = ensure_safe_output_dir(Path(args.output_dir), kicad_root, args.version)
    index = build_index(kicad_root)
    write_json(output_dir / "3d_model_index.json", index)
    write_summary(output_dir, index)
    print(f"Wrote {output_dir / '3d_model_index.json'}")
    print(f"Wrote {output_dir / '3d_model_summary.md'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
