#!/usr/bin/env python3
"""Build a read-only KiCad footprint library index."""

from __future__ import annotations

import argparse
import re
from pathlib import Path

from kicad_library_common import (
    default_output_dir,
    detect_kicad_root,
    ensure_safe_output_dir,
    fail,
    kicad_share_root,
    parse_lib_table,
    read_text,
    user_config_roots,
    utc_stamp,
    write_json,
    write_markdown,
)


DESCR_PATTERN = re.compile(r"\(descr\s+\"([^\"]*)\"")
TAGS_PATTERN = re.compile(r"\(tags\s+\"([^\"]*)\"")
PAD_PATTERN = re.compile(r"\(pad\s+\"?([^\"\s\)]+)\"?")
MODEL_PATTERN = re.compile(r"\(model\s+\"([^\"]+)\"")


def inspect_footprint(path: Path, library: str) -> dict[str, object]:
    text = read_text(path)
    pad_names = sorted(set(PAD_PATTERN.findall(text)), key=lambda value: (len(value), value))[:80]
    models = MODEL_PATTERN.findall(text)
    descr = DESCR_PATTERN.search(text)
    tags = TAGS_PATTERN.search(text)
    return {
        "library": library,
        "footprint": path.stem,
        "path": str(path),
        "description": descr.group(1) if descr else "",
        "tags": tags.group(1) if tags else "",
        "pad_count": len(PAD_PATTERN.findall(text)),
        "pad_names_sample": pad_names,
        "model_paths": models,
    }


def build_index(kicad_root: Path, version_preference: str) -> dict[str, object]:
    share = kicad_share_root(kicad_root)
    footprints_root = share / "footprints"
    template_root = share / "template"
    if not footprints_root.exists():
        fail(f"Footprint root not found: {footprints_root}")

    libraries = []
    footprints = []
    for lib_dir in sorted(footprints_root.glob("*.pretty")):
        lib_name = lib_dir.stem
        mods = sorted(lib_dir.glob("*.kicad_mod"))
        libraries.append({"library": lib_name, "path": str(lib_dir), "footprint_count": len(mods)})
        for mod in mods:
            footprints.append(inspect_footprint(mod, lib_name))

    table_paths = [template_root / "fp-lib-table"]
    for root in user_config_roots(version_preference):
        table_paths.append(root / "fp-lib-table")
    table_entries = []
    for table_path in table_paths:
        table_entries.extend(parse_lib_table(table_path))

    with_models = sum(1 for row in footprints if row["model_paths"])
    return {
        "generated_at": utc_stamp(),
        "kicad_root": str(kicad_root),
        "footprints_root": str(footprints_root),
        "user_config_roots": [str(p) for p in user_config_roots(version_preference)],
        "library_tables_read": [str(p) for p in table_paths if p.exists()],
        "summary": {
            "footprint_libraries": len(libraries),
            "footprints_indexed": len(footprints),
            "footprints_with_3d_model_refs": with_models,
            "footprint_table_entries": len(table_entries),
        },
        "libraries": libraries,
        "footprint_table_entries": table_entries,
        "footprints": footprints,
        "safety": [
            "Read-only inspection of KiCad install and user-global library tables.",
            "No KiCad install files are modified.",
            "No user-global library tables are modified.",
        ],
    }


def write_summary(output_dir: Path, index: dict[str, object]) -> None:
    summary = index["summary"]
    lines = [
        "# Footprint Index Summary",
        "",
        f"Generated: {index['generated_at']}",
        "",
        f"KiCad root: `{index['kicad_root']}`",
        f"Footprint root: `{index['footprints_root']}`",
        "",
        "## Counts",
        "",
        f"- Footprint libraries: {summary['footprint_libraries']}",
        f"- Footprints indexed: {summary['footprints_indexed']}",
        f"- Footprints with 3D model references: {summary['footprints_with_3d_model_refs']}",
        f"- Library table entries parsed: {summary['footprint_table_entries']}",
        "",
        "## Largest Libraries",
        "",
        "| Library | Footprints | Path |",
        "| --- | ---: | --- |",
    ]
    libraries = sorted(index["libraries"], key=lambda row: row["footprint_count"], reverse=True)[:25]
    for row in libraries:
        lines.append(f"| `{row['library']}` | {row['footprint_count']} | `{row['path']}` |")
    lines.extend(
        [
            "",
            "## Safety",
            "",
            "- This summary was generated by read-only filesystem inspection.",
            "- Candidate footprints still require package drawing, pad numbering, orientation, courtyard, paste/mask, and 3D review.",
        ]
    )
    write_markdown(output_dir / "footprint_index_summary.md", lines)


def main() -> int:
    parser = argparse.ArgumentParser(description="Build a read-only KiCad footprint index.")
    parser.add_argument("--kicad-root", help="KiCad install root. Defaults to detected KiCad 9 root.")
    parser.add_argument("--version", default="9.0", help="KiCad config version to inspect. Default: 9.0")
    parser.add_argument("--output-dir", default=str(default_output_dir()), help="Generated index output folder.")
    args = parser.parse_args()

    kicad_root = detect_kicad_root(args.kicad_root, args.version)
    if not kicad_root:
        fail("KiCad root not found. Pass --kicad-root.")
    output_dir = ensure_safe_output_dir(Path(args.output_dir), kicad_root, args.version)
    index = build_index(kicad_root, args.version)
    write_json(output_dir / "footprint_index.json", index)
    write_summary(output_dir, index)
    print(f"Wrote {output_dir / 'footprint_index.json'}")
    print(f"Wrote {output_dir / 'footprint_index_summary.md'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
